import supabase_db  # Module handling all Supabase database operations for bets/predictions
from models import Bet, Prediction, User  # Data models for Bet, Prediction, and User entities
from auth import is_admin, can_place_prediction  # Authorization checks from auth module
from scoring import distribute_reedz_on_resolution # Reedz distribution logic after bet resolution
from datetime import datetime  # For timestamping bet creation and predictions


def create_bet(admin_user: User, title: str, description: str, answer_type: str, close_at: datetime):
    """
    Creates a new bet event.
    
    Validates admin permissions and initializes bet with open status.
    
    Args:
        admin_user (User): Admin user creating the bet.
        title (str): Short title of the betting market.
        description (str): Detailed description of the event.
        answer_type (str): Type of answer expected (e.g., 'yes/no', 'numeric').
        close_at: Timestamp when betting closes.
    
    Returns:
        Bet: Created bet object from database.
    
    Raises:
        PermissionError: If user is not admin.
    """
    # Enforce admin-only access for bet creation
    if not is_admin(admin_user):
        raise PermissionError("Only admin can create bets")
    
    # Construct new Bet instance with default open/unresolved state
    bet = Bet(
        bet_id=None,  # Auto-generated by database on insert
        created_by_user_id=admin_user.user_id,
        title=title,
        description=description,
        answer_type=answer_type,
        is_open=True,  # Betting is active
        is_resolved=False,  # Answer not yet determined
        created_at=datetime.now(),  # Record creation timestamp
        close_at=close_at,  # Betting deadline
        resolved_at=None,  # Will be set on resolution
        correct_answer=None,  # Will be set by admin later
        is_closed=False  # Betting not closed yet
    )
    # Persist bet to Supabase database
    return supabase_db.create_bet(bet)


def close_bet(admin_user: User, bet_id: int):
    """
    Closes a bet prematurely (stops new predictions).
    
    Admin-only operation to end betting before resolution.
    
    Args:
        admin_user (User): Admin performing the close action.
        bet_id: Unique identifier of bet to close.
    
    Returns:
        bool: Success status from database update.
    
    Raises:
        PermissionError: If user is not admin.
    """
    # Enforce admin-only access for closing bets
    if not is_admin(admin_user):
        raise PermissionError("Only admin can close bets")
    
    # Update bet status in database (sets is_open=False)
    return supabase_db.close_bet(bet_id)


def resolve_bet(admin_user: User, bet_id, correct_answer):
    """
    Resolves a bet with the correct answer and triggers payouts.
    
    Admin sets final answer, then distributes Reedz rewards to winners.
    
    Args:
        admin_user (User): Admin resolving the bet.
        bet_id: Unique identifier of bet to resolve.
        correct_answer: The official correct answer value.
    
    Raises:
        PermissionError: If user is not admin.
    """
    # Enforce admin-only access for bet resolution
    if not is_admin(admin_user):
        raise PermissionError("Only admin can resolve bets")
    
    # Update bet with correct answer and resolved status in database
    supabase_db.resolve_bet(bet_id, correct_answer)
    
    # Trigger Reedz reward distribution to correct predictors
    distribute_reedz_on_resolution(bet_id) # This is equivalent to the return of the function


def place_prediction(user: User, bet_id, prediction_value):
    """
    Allows authorized user to place a prediction on an open bet.
    
    Enforces one prediction per user per bet rule.
    
    Args:
        user (User): User placing the prediction.
        bet_id: Target bet identifier.
        prediction_value: User's prediction (converted to string).
    
    Returns:
        Prediction: Created prediction object from database.
    
    Raises:
        PermissionError: If user lacks prediction permissions.
        Exception: If user already predicted on this bet.
    """
    # Check user authorization for placing predictions
    if not can_place_prediction(user):
        raise PermissionError("User cannot place predictions")
    
    # Prevent duplicate predictions by same user on same bet
    if supabase_db.has_prediction(user.user_id, bet_id):
        raise Exception("Only one prediction per user per bet")
    
    # Create Prediction instance with user's guess
    prediction = Prediction(
        prediction_id=None,  # Auto-generated by database
        user_id=user.user_id, # User placing the prediction
        bet_id=bet_id, # Target bet identifier
        prediction=str(prediction_value),  # Store as string for flexibility
        created_at=datetime.now()  # Timestamp prediction
    )
    
    # Save prediction to database
    return supabase_db.create_prediction(prediction)


def get_bet_overview(state: str):
    """
    Retrieves summary of bets filtered by state (open/closed/resolved).
    
    Args:
        state (str): Filter by bet state ('open', 'closed', 'resolved').
    
    Returns:
        List: Bet overview data from database query.
    """
    # Delegate to database layer for state-filtered bet summary
    return supabase_db.get_bet_overview(state)
